name: "ESP32 bluetin cnc Controller"
board: "ESP32 bluetin cnc Controller"

arc_tolerance_mm: 0.002
junction_deviation_mm: 0.010
verbose_errors: false
report_inches: false
enable_parking_override_control: false
use_line_numbers: true
planner_blocks: 16

stepping:
  engine: RMT
  idle_ms: 255
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 2

axes:
  shared_stepper_disable_pin: gpio.13:low
  
  x:
    steps_per_mm: 53.333
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 563
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: -150
      positive_direction: false
      feed_mm_per_min: 50.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100
    
    motor0:
      limit_all_pin: gpio.34:low
      hard_limits: true
      pulloff_mm:5.000
      stepstick:
        direction_pin: gpio.14
        step_pin: gpio.12

  y:
    steps_per_mm: 53.333
    max_rate_mm_per_min: 5000
    acceleration_mm_per_sec2: 50
    max_travel_mm: 746
    soft_limits: true
    homing:
      cycle: 2
      mpos_mm: -150
      positive_direction: false
      feed_mm_per_min: 50.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.35:low
      hard_limits: true
      pulloff_mm:5.000
      stepstick:
        direction_pin: gpio.15
        step_pin: gpio.26

  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 500
    acceleration_mm_per_sec2: 10
    max_travel_mm: 68
    soft_limits: true
    homing:
      cycle: 1
      mpos_mm: 10
      positive_direction: true
      feed_mm_per_min: 50.000
      seek_mm_per_min: 2000.000
      settle_ms: 500
      seek_scaler: 1.100
      feed_scaler: 1.100

    motor0:
      limit_all_pin: gpio.36:low
      hard_limits: true
      pulloff_mm:5.000
      stepstick:
        direction_pin: gpio.33
        step_pin: gpio.27

spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18

sdcard:
  cs_pin: gpio.5
  card_detect_pin: NO_PIN

coolant:
  flood_pin: NO_PIN
  mist_pin:  NO_PIN

        
probe:
  pin: gpio.32:low

