site_name: Hacman - Ox CNC
site_url: https://hacmanchester.github.io/Tools.OxCNC/
repo_url: https://github.com/HACManchester/Tools.OxCNC/
site_description: Hacman - Ox CNC
edit_uri: edit/master/MkDocs/docs

pages:
- Home: index.md
#- CAM:
#    - JSCut:
#- FreeCAD:
#    - File Importing: FreeCad/File-Import.md
#    - Exporting GCode: FreeCad/Export-GCode.md
#- Hsmworks:
#    - Adaptive Clearing: Hsmworks/AdaptClear.md
#    - Simulation: Hsmworks/Simulation.md
- Milling:
    - Connecting: Milling/Connecting.md
    - Jogging / Moving the CNC: Milling/Jog.md
    - Loading and Setup: Milling/Loading-Setup.md
    - Simulation: Milling/Simulation.md
    - Milling Material: Milling/Material.md
    - Feed Rates: Milling/FeedRates.md
    - Milling: Milling/Milling.md
- PCB:
    - Installing FlatCAM: PCB/Installing-FlatCAM.md
- Other:
    - Machinable Wax: Other/MachinableWax.md
- Maintenance:
    - Device Overview: Maintenance/Device-Overview.md
    - Updating the Firmware: Maintenance/Updating-Firmware.md
    - Grbl Settings: Maintenance/Grbl-Settings.md
    - Todo: Maintenance/Todo.md
    - Electronics Upgrade: Maintenance/Electronics-Upgrade.md

theme: cosmo
#theme: alabaster
#theme: readthedocs
#theme: mkdocs

# Overrides content within the selected theme
theme_dir: theme

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
    - css/navbarfix.css
